### ISSUE TITLE
There were some problems running the utest.py test file?

### ISSUE THREAD

**Issue by biaogxb** [leetmaa/KMCLib#30]
when I running the utest.py test file and KMC operation terminated suddenly

Then the error is reported as follows：

Traceback (most recent call last):
  File "utest.py", line 13, in <module>
    from KMCLibTest import KMCLibTests
  File "/home/biao/KMCLib-master/python/unittest/KMCLibTest/KMCLibTests.py", line 14, in <module>
    from .CoreComponents import CoreComponentsTests
  File "/home/biao/KMCLib-master/python/unittest/KMCLibTest/CoreComponents/CoreComponentsTests.py", line 15, in <module>
    from .KMCLatticeModelTest import KMCLatticeModelTest
  File "/home/biao/KMCLib-master/python/unittest/KMCLibTest/CoreComponents/KMCLatticeModelTest.py", line 604
    exec(compile(open(trajectory_filename, "rb").read(), trajectory_filename, 'exec'), global_dict, local_dict)
SyntaxError: unqualified exec is not allowed in function 'testRunNoMatch' it contains a nested function with free variables

Does anyone know what the problem is？

**Comment by lilyhuo129** [comment]
> when I running the utest.py test file and KMC operation terminated suddenly
> 
> Then the error is reported as follows：
> 
> Traceback (most recent call last): File "utest.py", line 13, in from KMCLibTest import KMCLibTests File "/home/biao/KMCLib-master/python/unittest/KMCLibTest/KMCLibTests.py", line 14, in from .CoreComponents import CoreComponentsTests File "/home/biao/KMCLib-master/python/unittest/KMCLibTest/CoreComponents/CoreComponentsTests.py", line 15, in from .KMCLatticeModelTest import KMCLatticeModelTest File "/home/biao/KMCLib-master/python/unittest/KMCLibTest/CoreComponents/KMCLatticeModelTest.py", line 604 exec(compile(open(trajectory_filename, "rb").read(), trajectory_filename, 'exec'), global_dict, local_dict) SyntaxError: unqualified exec is not allowed in function 'testRunNoMatch' it contains a nested function with free variables
> 
> Does anyone know what the problem is？

I also face this issue when running on CentOs.
