### ISSUE TITLE
Problem in running utest.py: ModuleNotFoundError: No module named 'Analysis'

### ISSUE THREAD

**Issue by a-firdaus** [leetmaa/KMCLib#31]
I use python 3.8 for installing KMCLib version 2.0-a1

I have an error, it says no module named 'Analysis':
`Traceback (most recent call last): 
  File "utest.py", line 13, in <module>
    from KMCLibTest import KMCLibTests
  File "/home/azka/02_Software/KMCLib-2.0-a1/python/unittest/KMCLibTest/KMCLibTests.py", line 12, in <module>
    from Analysis import AnalysisTests
ModuleNotFoundError: No module named 'Analysis'
`

Eventhough I had installed it before successfully
`$ python3.8 -m pip install analysis
Requirement already satisfied: analysis in /home/azka/anaconda3/envs/kmclib2/lib/python3.8/site-packages (0.1.7)
`

Do you know why does this happen?

**Comment by jalchemy** [comment]
Just encountered the same issue with KMCLib-1.1.1.

The solution for me was to explicitly add the location of modules required by KMCLibTests.py to the PYTHONPATH, i.e. add the following to your `.bashrc`:
`export PYTHONPATH=<path-to-KMCLib-dir>KMCLib-1.1.1/python/unittest/KMCLibTest:${PYTHONPATH}`

Unfortunately I get further errors testing the python backend that prevent me from confirming I can get a working setup, but the above should at least get you past these module import errors.
